# Generated by Django 5.2.9 on 2026-01-03 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_comment_down_voters_comment_up_voters_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
